#!/usr/bin/env python3
"""Generates the README results tables from results/*.json (written by scripts/bench.py).

    python3 scripts/ladder.py            # rewrite the text between the markers in README.md
    python3 scripts/ladder.py --check    # exit 1 if README.md differs from what would be written

The table in the README is never edited by hand. `--check` runs in CI, so a hand-edited (or
stale) table fails the build: it regenerates the table from the committed results files and
compares it with the README byte for byte.

Standard library only.
"""
import argparse
import difflib
import json
import os
import sys

from bench import BenchError, load_configs, load_expected

START_MARKER = "<!-- ladder:start -->"
END_MARKER = "<!-- ladder:end -->"
SCRIPT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

NOISY_MARK = "†"      # dagger
REGRESSION_MARK = "▼"  # down-pointing triangle
TIMES = "×"           # multiplication sign


class LadderError(Exception):
    pass


# ----------------------------------------------------------------------------- loading


def load_results(root, configs):
    """Returns {config id: parsed results file} for every config that has one."""
    results = {}
    for config in configs:
        path = os.path.join(root, "results", config["id"] + ".json")
        if not os.path.exists(path):
            continue
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            if data["config"]["id"] != config["id"]:
                raise LadderError(f"{path}: config id {data['config']['id']!r} does not match "
                                  "its file name")
            data["meta"]["commit"], data["benchmarks"]  # must exist
        except (OSError, ValueError, KeyError, TypeError) as e:
            raise LadderError(f"{path}: not a results file written by bench.py ({e!r})")
        results[config["id"]] = data
    return results


# ----------------------------------------------------------------------------- rendering


def cell_entry(results, config_id, benchmark):
    """The summary for one (config, benchmark), or None if it was not measured."""
    data = results.get(config_id)
    return data["benchmarks"].get(benchmark) if data else None


def per_iteration_ns(entry):
    # Normalised by iteration count so results taken with different --iterations compare.
    return entry["median_total_ns"] / entry["iterations"]


def ratio_cell(numerator, denominator):
    """Both arguments are summary entries (or None). The result is how many times faster the
    `denominator` entry is than the `numerator` one: the reference's time over the row's."""
    if numerator is None or denominator is None:
        return "n/a"
    ratio = per_iteration_ns(numerator) / per_iteration_ns(denominator)
    text = f"{ratio:.2f}{TIMES}"
    if ratio < 1.0:
        text = f"**{text} {REGRESSION_MARK}**"
    if numerator["noisy"] or denominator["noisy"]:
        text += " " + NOISY_MARK
    return text


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(" --- " for _ in header) + "|"]
    lines += ["| " + " | ".join(cells) + " |" for cells in rows]
    return "\n".join(lines)


def row_name(config):
    return f"`{config['id']}` {config['label']}".replace("|", "\\|")


def machine_text(meta):
    return f"{meta['cpu']}, {meta['os']}".replace("|", "\\|")


def render(root):
    """The generated README text (without the markers)."""
    configs = load_configs(root)
    benchmarks = list(load_expected(root))
    results = load_results(root, configs)
    base = configs[0]
    out = ["_This section is generated by `scripts/ladder.py` from the files in `results/`. "
           "Do not edit it by hand: `ladder.py --check` runs in CI and fails if it differs._"]

    if not results:
        out += ["", "No results have been recorded yet. Each row appears here once "
                "`scripts/bench.py` has measured it on the development machine (notes D5)."]
        return "\n".join(out)

    # Table 1: cumulative speedup over the first row.
    rows = []
    for config in configs:
        cells = [row_name(config)]
        for b in benchmarks:
            if config["id"] not in results:
                cells.append("not measured")
            else:
                cells.append(ratio_cell(cell_entry(results, base["id"], b),
                                        cell_entry(results, config["id"], b)))
        rows.append(cells)
    out += ["", f"**Speedup over `{base['id']}`** (median time of one `run()` call, per-run "
            "totals, higher is faster):", "", table(["Configuration"] + benchmarks, rows)]

    # Table 2: marginal speedup over the previous row.
    rows = []
    for i, config in enumerate(configs):
        cells = [row_name(config)]
        for b in benchmarks:
            if config["id"] not in results:
                cells.append("not measured")
            elif i == 0:
                cells.append("—")
            else:
                cells.append(ratio_cell(cell_entry(results, configs[i - 1]["id"], b),
                                        cell_entry(results, config["id"], b)))
        rows.append(cells)
    out += ["", "**Marginal speedup over the previous row:**", "",
            table(["Configuration"] + benchmarks, rows)]

    # Table 3: per-iteration p99.
    rows = []
    for config in configs:
        cells = [row_name(config)]
        for b in benchmarks:
            entry = cell_entry(results, config["id"], b)
            if config["id"] not in results:
                cells.append("not measured")
            elif entry is None:
                cells.append("n/a")
            else:
                cells.append(f"{entry['p99_ns'] / 1e6:.2f} ms" +
                             (" " + NOISY_MARK if entry["noisy"] else ""))
        rows.append(cells)
    out += ["", "**p99 time of one `run()` call** (nearest-rank, over every measured call of "
            "every run pooled; lower is better):", "",
            table(["Configuration"] + benchmarks, rows)]

    # Table 4: where each row came from.
    rows = []
    for config in configs:
        data = results.get(config["id"])
        if data is None:
            continue
        meta = data["meta"]
        rows.append([row_name(config),
                     "`" + meta["commit"][:10] + "`" + (" (dirty)" if meta.get("dirty") else ""),
                     meta["date"][:10], machine_text(meta),
                     meta["power_source"].replace("|", "\\|"),
                     f"{meta['kept_runs']} runs of {meta['iterations']} calls"])
    out += ["", "**Provenance** (from `meta` in each results file):", "",
            table(["Configuration", "Commit", "Date", "Machine", "Power", "Measured"], rows)]

    out += ["", f"{REGRESSION_MARK} marks a configuration slower than the one it is compared "
            f"with. {NOISY_MARK} marks a cell where the spread (IQR) of the per-run totals "
            "exceeded 5% of their median in at least one of the two runs compared, so the "
            "figure is uncertain and the row should be re-measured."]
    return "\n".join(out)


# ----------------------------------------------------------------------------- README


def split_readme(text):
    """Returns (before, current block, after) around the markers."""
    start, end = text.find(START_MARKER), text.find(END_MARKER)
    if start < 0 or end < 0 or end < start or text.count(START_MARKER) != 1 \
            or text.count(END_MARKER) != 1:
        raise LadderError(f"README.md needs exactly one {START_MARKER} followed by one "
                          f"{END_MARKER}")
    before = text[:start + len(START_MARKER)]
    block = text[start + len(START_MARKER):end]
    return before, block, text[end:]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README.md does not match the results files")
    parser.add_argument("--root", default=SCRIPT_ROOT, help=argparse.SUPPRESS)  # for tests
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)
    readme_path = os.path.join(args.root, "README.md")
    try:
        with open(readme_path, encoding="utf-8") as f:
            readme = f.read()
        before, current, after = split_readme(readme)
        wanted = "\n" + render(args.root) + "\n"
    except (LadderError, BenchError, OSError) as e:
        print("ladder.py: " + str(e), file=sys.stderr)
        return 2

    if args.check:
        if current == wanted:
            print("README.md results table matches results/*.json")
            return 0
        diff = difflib.unified_diff(current.splitlines(), wanted.splitlines(),
                                    "README.md (committed)", "generated from results/",
                                    lineterm="", n=1)
        print("\n".join(diff), file=sys.stderr)
        print("\nladder.py: the README results table is not what results/*.json generate. "
              "Never edit it by hand; run `python3 scripts/ladder.py` and commit the result.",
              file=sys.stderr)
        return 1

    if current == wanted:
        print("README.md is already up to date")
        return 0
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(before + wanted + after)
    print("updated the results table in README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
