// Hand-written ARM64 (AArch64) instruction encoder for the JIT (notes D3). No LLVM, no asmjit:
// every instruction is a 32-bit word we assemble ourselves from bit fields. It only produces
// bytes; executing them is a separate concern. It compiles on every platform so the encodings
// are tested everywhere, even though the JIT itself only runs on ARM64.
//
// Every encoding is checked byte-for-byte against the LLVM assembler through the committed table
// tests/unit/arm64_encodings.inc (generated by scripts/gen_arm64_table.py).
#pragma once

#include <concepts>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <vector>

namespace rung::arm64 {

// Thrown for anything we cannot encode: an immediate or branch offset out of range, a
// misaligned offset, a register that is illegal in that slot, a label problem. Never silent.
class EmitError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

// Register numbers 0..30 encode as themselves. Register field 31 means "zero register" in some
// instruction slots and "stack pointer" in others, so the enums give them distinct values (SP is
// 32) and the encoder turns the right one into 31, rejecting the wrong one. That catches
// `add x0, xzr, #1` (which the hardware would silently execute as `add x0, sp, #1`).
// W registers are the low 32 bits of the matching X register (notes D1: Rung ints are 32-bit).
// clang-format off
enum WReg : uint8_t {
    W0, W1, W2, W3, W4, W5, W6, W7, W8, W9, W10, W11, W12, W13, W14, W15, W16,
    W17, W18, W19, W20, W21, W22, W23, W24, W25, W26, W27, W28, W29, W30,
    WZR,       // 31: reads as zero, writes discarded
    WSP = 32,  // the stack pointer, low 32 bits
};
enum XReg : uint8_t {
    X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16,
    X17, X18, X19, X20, X21, X22, X23, X24, X25, X26, X27, X28, X29, X30,
    XZR,
    SP = 32,
};
// clang-format on

// The 4-bit condition field. Aliases (CS/HS, CC/LO) share a value.
enum class Cond : uint8_t {
    EQ = 0,
    NE,
    CS,
    CC,
    MI,
    PL,
    VS,
    VC,
    HI,
    LS,
    GE,
    LT,
    GT,
    LE,
    AL,
    HS = CS,
    LO = CC,
};

template <class R>
concept GpReg = std::same_as<R, WReg> || std::same_as<R, XReg>;

// A forward-referenceable branch target handed out by Emitter::make_label().
struct Label {
    uint32_t id;
};

enum class AddSub : uint8_t { Add, Sub, Adds, Subs };
enum class Logic : uint8_t { And, Orr, Eor, Ands };
enum class Shift : uint8_t { Lsl, Lsr, Asr };
enum class Wide : uint8_t { Movz, Movn, Movk };
enum class Writeback : uint8_t { Post, Pre };

class Emitter {
public:
    // ---- arithmetic -------------------------------------------------------------------------
    template <GpReg R> void add(R d, R n, R m) { addsub_reg_(AddSub::Add, is64<R>, d, n, m); }
    template <GpReg R> void sub(R d, R n, R m) { addsub_reg_(AddSub::Sub, is64<R>, d, n, m); }
    template <GpReg R> void adds(R d, R n, R m) { addsub_reg_(AddSub::Adds, is64<R>, d, n, m); }
    template <GpReg R> void subs(R d, R n, R m) { addsub_reg_(AddSub::Subs, is64<R>, d, n, m); }
    // imm12 is 0..4095; shift12 means the immediate is shifted left by 12. n may be SP; so may
    // d for add/sub (for adds/subs, d = 31 is the zero register instead).
    template <GpReg R> void add_imm(R d, R n, uint32_t imm12, bool shift12 = false) {
        addsub_imm_(AddSub::Add, is64<R>, d, n, imm12, shift12);
    }
    template <GpReg R> void sub_imm(R d, R n, uint32_t imm12, bool shift12 = false) {
        addsub_imm_(AddSub::Sub, is64<R>, d, n, imm12, shift12);
    }
    template <GpReg R> void adds_imm(R d, R n, uint32_t imm12, bool shift12 = false) {
        addsub_imm_(AddSub::Adds, is64<R>, d, n, imm12, shift12);
    }
    template <GpReg R> void subs_imm(R d, R n, uint32_t imm12, bool shift12 = false) {
        addsub_imm_(AddSub::Subs, is64<R>, d, n, imm12, shift12);
    }
    // CMP is SUBS with the result thrown away into the zero register.
    template <GpReg R> void cmp(R n, R m) { subs(zero<R>(), n, m); }
    template <GpReg R> void cmp_imm(R n, uint32_t imm12, bool shift12 = false) {
        subs_imm(zero<R>(), n, imm12, shift12);
    }
    // NEG is 0 - m.
    template <GpReg R> void neg(R d, R m) { sub(d, zero<R>(), m); }
    // MADD: d = a + n*m.  MUL is MADD with a = zero.  MSUB: d = a - n*m (used for %).
    template <GpReg R> void madd(R d, R n, R m, R a) { mul_add_(false, is64<R>, d, n, m, a); }
    template <GpReg R> void msub(R d, R n, R m, R a) { mul_add_(true, is64<R>, d, n, m, a); }
    template <GpReg R> void mul(R d, R n, R m) { madd(d, n, m, zero<R>()); }
    template <GpReg R> void sdiv(R d, R n, R m) { sdiv_(is64<R>, d, n, m); }

    // ---- logic and shifts -------------------------------------------------------------------
    template <GpReg R> void and_(R d, R n, R m) { logic_reg_(Logic::And, is64<R>, d, n, m); }
    template <GpReg R> void orr(R d, R n, R m) { logic_reg_(Logic::Orr, is64<R>, d, n, m); }
    template <GpReg R> void eor(R d, R n, R m) { logic_reg_(Logic::Eor, is64<R>, d, n, m); }
    template <GpReg R> void tst(R n, R m) { logic_reg_(Logic::Ands, is64<R>, zero<R>(), n, m); }
    // Immediate shifts are bitfield moves (UBFM/SBFM). amount is 0..31 (W) or 0..63 (X).
    template <GpReg R> void lsl(R d, R n, unsigned amount) {
        shift_imm_(Shift::Lsl, is64<R>, d, n, amount);
    }
    template <GpReg R> void lsr(R d, R n, unsigned amount) {
        shift_imm_(Shift::Lsr, is64<R>, d, n, amount);
    }
    template <GpReg R> void asr(R d, R n, unsigned amount) {
        shift_imm_(Shift::Asr, is64<R>, d, n, amount);
    }

    // ---- moves ------------------------------------------------------------------------------
    // imm16 is 0..65535; shift is 0/16 (W) or 0/16/32/48 (X).
    template <GpReg R> void movz(R d, uint32_t imm16, unsigned shift = 0) {
        wide_(Wide::Movz, is64<R>, d, imm16, shift);
    }
    template <GpReg R> void movn(R d, uint32_t imm16, unsigned shift = 0) {
        wide_(Wide::Movn, is64<R>, d, imm16, shift);
    }
    template <GpReg R> void movk(R d, uint32_t imm16, unsigned shift = 0) {
        wide_(Wide::Movk, is64<R>, d, imm16, shift);
    }
    // Register move. ORR d, zr, n normally; ADD d, n, #0 when SP is involved (ORR cannot read
    // or write SP).
    void mov(WReg d, WReg n);
    void mov(XReg d, XReg n);
    // Materialise any constant in the fewest MOVZ/MOVN/MOVK instructions (bitmask-immediate ORR
    // forms are not used, so a few patterns like 0x00FF00FF00FF00FF take four instead of one).
    void mov_imm(WReg d, uint32_t value);
    void mov_imm(XReg d, uint64_t value);

    // ---- memory -----------------------------------------------------------------------------
    // Unsigned scaled-immediate offset: byte_offset must be a multiple of the access size (4 for
    // W, 8 for X) and at most 4095 accesses. base may be SP.
    template <GpReg R> void ldr(R rt, XReg base, uint32_t byte_offset = 0) {
        ldr_str_(true, is64<R>, rt, base, byte_offset);
    }
    template <GpReg R> void str(R rt, XReg base, uint32_t byte_offset = 0) {
        ldr_str_(false, is64<R>, rt, base, byte_offset);
    }
    // Pair load/store with base-register writeback, for prologues and epilogues. The offset is
    // a multiple of the register size in -64*size .. 63*size. Post-index uses the base then
    // updates it; pre-index updates it first (`stp x29, x30, [sp, #-16]!`).
    template <GpReg R> void ldp_post(R t1, R t2, XReg base, int32_t byte_offset) {
        pair_(true, Writeback::Post, is64<R>, t1, t2, base, byte_offset);
    }
    template <GpReg R> void ldp_pre(R t1, R t2, XReg base, int32_t byte_offset) {
        pair_(true, Writeback::Pre, is64<R>, t1, t2, base, byte_offset);
    }
    template <GpReg R> void stp_post(R t1, R t2, XReg base, int32_t byte_offset) {
        pair_(false, Writeback::Post, is64<R>, t1, t2, base, byte_offset);
    }
    template <GpReg R> void stp_pre(R t1, R t2, XReg base, int32_t byte_offset) {
        pair_(false, Writeback::Pre, is64<R>, t1, t2, base, byte_offset);
    }

    // ---- control flow -----------------------------------------------------------------------
    // Raw forms take a byte offset from this instruction (multiple of 4). B/BL reach +-128 MiB,
    // B.cond/CBZ/CBNZ reach +-1 MiB. Label forms may refer to a label bound later.
    void b_offset(int64_t byte_offset);
    void bl_offset(int64_t byte_offset);
    void b_cond_offset(Cond c, int64_t byte_offset);
    template <GpReg R> void cbz_offset(R rt, int64_t byte_offset) {
        cbz_(false, is64<R>, rt, byte_offset);
    }
    template <GpReg R> void cbnz_offset(R rt, int64_t byte_offset) {
        cbz_(true, is64<R>, rt, byte_offset);
    }
    void b(Label l);
    void bl(Label l);
    void b_cond(Cond c, Label l);
    template <GpReg R> void cbz(R rt, Label l) { cbz_label_(false, is64<R>, rt, l); }
    template <GpReg R> void cbnz(R rt, Label l) { cbz_label_(true, is64<R>, rt, l); }
    void br(XReg n);
    void blr(XReg n);
    void ret(XReg n = X30);
    // d = (cond ? 1 : 0). c must not be AL.
    template <GpReg R> void cset(R d, Cond c) { cset_(is64<R>, d, c); }

    // ---- labels -----------------------------------------------------------------------------
    Label make_label();
    // Bind to the current position and patch every earlier branch that targeted it.
    void bind(Label l);
    // Throws if any branch still points at an unbound label. Call once code is complete.
    void finish() const;

    // ---- output -----------------------------------------------------------------------------
    const std::vector<uint32_t>& code() const { return code_; }
    size_t size_bytes() const { return code_.size() * 4; }
    // Append one raw word (also what every instruction above ends up calling).
    void emit(uint32_t word) { code_.push_back(word); }

private:
    template <class R> static constexpr bool is64 = std::same_as<R, XReg>;
    template <class R> static constexpr R zero() {
        if constexpr (is64<R>) {
            return XZR;
        } else {
            return WZR;
        }
    }

    enum class Fixup : uint8_t { Imm26, Imm19 };
    struct Pending {
        size_t index;
        Fixup kind;
    };
    struct LabelState {
        bool bound = false;
        size_t index = 0;  // instruction index of the bind point
        std::vector<Pending> pending;
    };

    // Register arguments are passed as plain numbers (0..30 = registers, 31 = ZR, 32 = SP) so
    // the non-template bodies live in the .cpp.
    void addsub_reg_(AddSub op, bool sf, unsigned d, unsigned n, unsigned m);
    void addsub_imm_(AddSub op, bool sf, unsigned d, unsigned n, uint32_t imm12, bool shift12);
    void mul_add_(bool subtract, bool sf, unsigned d, unsigned n, unsigned m, unsigned a);
    void sdiv_(bool sf, unsigned d, unsigned n, unsigned m);
    void logic_reg_(Logic op, bool sf, unsigned d, unsigned n, unsigned m);
    void shift_imm_(Shift op, bool sf, unsigned d, unsigned n, unsigned amount);
    void wide_(Wide op, bool sf, unsigned d, uint32_t imm16, unsigned shift);
    void ldr_str_(bool load, bool sf, unsigned rt, unsigned base, uint32_t byte_offset);
    void pair_(bool load, Writeback wb, bool sf, unsigned t1, unsigned t2, unsigned base,
               int32_t byte_offset);
    void cbz_(bool nonzero, bool sf, unsigned rt, int64_t byte_offset);
    void cbz_label_(bool nonzero, bool sf, unsigned rt, Label l);
    void cset_(bool sf, unsigned d, Cond c);
    void branch_to_label_(uint32_t word, Fixup kind, Label l);
    void patch_(size_t index, Fixup kind, size_t target_index);

    std::vector<uint32_t> code_;
    std::vector<LabelState> labels_;
};

}  // namespace rung::arm64
